### ISSUE TITLE
Not load html?

### ISSUE THREAD

**Issue by joserick** [markwalet/nova-modal-response#1]
Hi, 

Hello, Thanks for the repository, it is exactly what I was looking for but I see that it no loads html, can you implement this functionality in the future?

Thanks.

![image](https://user-images.githubusercontent.com/15143699/220180953-19997868-ba4d-462a-a499-c2a48cfcaa23.png)

**Comment by markwalet** [comment]
Hi there,

It's already in there, but still undocumented. Try supplying the html array key instead of the body.

**Comment by joserick** [comment]
Thanks! It works.

Yes it's important to add it to the documentation.

**Comment by markwalet** [comment]
It's added to the documentation now.
