### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by patka-123** [markwalet/nova-modal-response#6]
Hello,

Would it be possible to give this package Laravel 11 compatability?

**Comment by markwalet** [comment]
Absolutely. I thought I had all the packages upgraded already, but apparently I forgot a few. Will do this today!

**Comment by markwalet** [comment]
Fixed in v0.3.0

**Comment by cyberwizard-dev** [comment]
Hello, Action runs but the modal not displaying.
`<?php

namespace App\Nova\Actions;

use App\Traits\GetModelDetails;
use App\Traits\ValidatesAccessCode;
use Illuminate\Support\Facades\Log;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Http;
use Laravel\Nova\Actions\ActionResponse;

class FetchSinglePricing extends Action
{
    use GetModelDetails;

    public $withoutActionEvents = true;
    public function handle (ActionFields $fields, Collection $models): ActionResponse|Action
    {
        if ($models->count() > 1) {
            return Action::danger('Please run this action on only one model.');
        }



        $id = $this->getModelId($models);


        $response = Http::get("url/{$id}");

        if ($response->successful()) {
            return Action::modal('modal-response', [
                'title' => 'Pricing Information',
                'html' => view('nova.pricing-modal', ['data' => $response->json()['data']])->render(),
            ]);
        }


        return ActionResponse::danger('Failed to fetch pricing information.');
    }
}

`

**Comment by markwalet** [comment]
Hi, thanks for raising the issue. Can you open a new ticket with this bug please? It'd help if you also provided the exact Laravel and Nova versions you have installed.

Thanks in advance!

**Comment by cyberwizard-dev** [comment]
Sorry about that. Laravel 11 and Nova v4

**Comment by markwalet** [comment]
Can you give me the exact versions and put them in a new ticket?

**Comment by cyberwizard-dev** [comment]
Yeah, I can. I'm on it.
