### ISSUE TITLE
Why  html code in 'html'key is not rendered ?

### ISSUE THREAD

**Issue by sergeynilov** [markwalet/nova-modal-response#8]
In Laravel 10 / nova 4.27 app I added "markwalet/nova-modal-response": "^0.3.0" and made response in action 
putting generated html code into 'html'key:

```
class CheckBannedUsers extends Action
{
    use InteractsWithQueue, Queueable;

    public $confirmText = 'Information on banned users would be shown';
    public function handle(ActionFields $fields, Collection $models)
    {
        $html = '<table>';
        $bannedUsers = User::getOnlyBanned()->orderBy('banned_at', 'desc')->get();

        foreach ($bannedUsers as $bannedUser) {
            $html .= '<tr><td>' .
                     $bannedUser->name . '(' . $bannedUser->email . ')' . '<\td><td>' .
                     $bannedUser->id .
                     '<\td><\tr>';
        }
        $html .= '<\table>';

        \Log::info($html);
        return Action::modal('modal-response', [
            'title' => 'Information on banned users',
            'html' => $html,
        ]);

    }

```
            
But I see html code (with first tags cut off ) :
            
            https://img001.prntscr.com/file/img001/B5hU-pTWRB649ixsy5sXGw.png            

Checking log with $html var content I see :
            
`[2024-11-11 14:34:15] local.INFO: <table><tr><td>TonyBlack(tony_black@site.com)<\td><td>3<\td><\tr><tr><td>User Marco Morar(arden.gottlieb@example.org)<\td><td>13<\td><\tr><tr><td>User Dr. Noel Kris(mraz.brett@example.com)<\td><td>16<\td><\tr><tr><td>User Prof. Tiana Stehr(fmills@example.com)<\td><td>21<\td><\tr><\table>
`      
The html code seems valid, but why it is not rendered ?

**Comment by markwalet** [comment]
It looks like you're using `<\td>` & `<\tr>` to close your html tags. You should use `</td>` & `</tr>` instead.

**Comment by sergeynilov** [comment]
Thanks!
